version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: vtrade_backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - DJANGO_SECRET_KEY=your_secret_key
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vtrade_frontend
    volumes:
      - ./frontend/vtrade:/app
      - /app/node_modules 
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:13-alpine 
    container_name: vtrade_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=goalcrest_db
    ports:
      - "5433:5432"

volumes:
  db_data:
